CREATE TABLE produit
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nom         VARCHAR(255),
    description VARCHAR(255),
    prix        DOUBLE PRECISION                         NOT NULL,
    quantite    INTEGER                                  NOT NULL,
    image       VARCHAR(255),
    category_id INTEGER,
    CONSTRAINT pk_produit PRIMARY KEY (id)
);

ALTER TABLE produit
    ADD CONSTRAINT FK_PRODUIT_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES pg_settings.category (id);