CREATE TABLE cart
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status     VARCHAR(255),
    total      DOUBLE PRECISION                        NOT NULL,
    user_id    INTEGER                                 NOT NULL,
    produit_id INTEGER                                 NOT NULL,
    quantite   INTEGER                                 NOT NULL,
    CONSTRAINT pk_cart PRIMARY KEY (id)
);

CREATE TABLE cart_item
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cart_id    INTEGER                                 NOT NULL,
    produit_id INTEGER                                 NOT NULL,
    quantite   INTEGER                                 NOT NULL,
    status     VARCHAR(255),
    CONSTRAINT pk_cartitem PRIMARY KEY (id)
);

CREATE TABLE category
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nom         VARCHAR(255),
    description VARCHAR(255),
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE "order"
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date    VARCHAR(255),
    status  VARCHAR(255),
    total   DOUBLE PRECISION                         NOT NULL,
    user_id INTEGER,
    CONSTRAINT pk_order PRIMARY KEY (id)
);

CREATE TABLE order_item
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id   INTEGER                                  NOT NULL,
    produit_id INTEGER                                  NOT NULL,
    quantite   INTEGER                                  NOT NULL,
    prix       INTEGER                                  NOT NULL,
    status     VARCHAR(255),
    CONSTRAINT pk_orderitem PRIMARY KEY (id)
);

CREATE TABLE produit
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nom         VARCHAR(255),
    description VARCHAR(255),
    prix        DOUBLE PRECISION                         NOT NULL,
    quantite    INTEGER                                  NOT NULL,
    image       VARCHAR(255),
    category_id INTEGER,
    CONSTRAINT pk_produit PRIMARY KEY (id)
);

CREATE TABLE "user"
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nom      VARCHAR(255),
    prenom   VARCHAR(255),
    email    VARCHAR(255),
    password VARCHAR(255),
    role     VARCHAR(255),
    cart_id  BIGINT,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE cart_item
    ADD CONSTRAINT FK_CARTITEM_ON_CART FOREIGN KEY (cart_id) REFERENCES cart (id);

ALTER TABLE cart_item
    ADD CONSTRAINT FK_CARTITEM_ON_PRODUIT FOREIGN KEY (produit_id) REFERENCES produit (id);

ALTER TABLE order_item
    ADD CONSTRAINT FK_ORDERITEM_ON_ORDER FOREIGN KEY (order_id) REFERENCES "order" (id);

ALTER TABLE "order"
    ADD CONSTRAINT FK_ORDER_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

ALTER TABLE produit
    ADD CONSTRAINT FK_PRODUIT_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES category (id);

ALTER TABLE "user"
    ADD CONSTRAINT FK_USER_ON_CART FOREIGN KEY (cart_id) REFERENCES cart (id);